# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AutolayoutDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AutolayoutDemo
  pod 'Masonry'
  pod 'AFNetworking'
  pod 'SSZipArchive'

  target 'AutolayoutDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AutolayoutDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
